org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.8
loader_version=0.16.14
loom_version=1.10.5

version=1.0.0+mc1.21.8
group=dev.goldenegg
fabric_api_version=0.129.0+1.21.8
modmenu_version=15.0.0
minecraft_dependency=1.21.8
fabric_api_dependency=>=0.129.0
