# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - minecraft-version: '1.21'
            fabric-api-version: '0.100.8+1.21'
            artifact-suffix: 'mc1.21'
          - minecraft-version: '1.21.1'
            fabric-api-version: '0.116.15+1.21.1'
            artifact-suffix: 'mc1.21.1'
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: >-
          ./gradlew build
          -Pminecraft_version=${{ matrix.minecraft-version }}
          -Pfabric_api_version=${{ matrix.fabric-api-version }}
      - name: capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts-${{ matrix.artifact-suffix }}
          path: build/libs/
