name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - minecraft-version: '1.21.2'
            fabric-api-version: '0.106.1+1.21.2'
          - minecraft-version: '1.21.3'
            fabric-api-version: '0.114.1+1.21.3'
          - minecraft-version: '1.21.4'
            fabric-api-version: '0.119.2+1.21.4'
    steps:
      - uses: actions/checkout@v6
      - uses: gradle/actions/wrapper-validation@v6
      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'microsoft'
      - run: chmod +x ./gradlew
      - name: build
        run: >-
          ./gradlew build
          -Pminecraft_version=${{ matrix.minecraft-version }}
          -Pfabric_api_version=${{ matrix.fabric-api-version }}
          -Pversion=1.0.0+mc${{ matrix.minecraft-version }}
          -Pminecraft_dependency=${{ matrix.minecraft-version }}
          -Pfabric_api_dependency=">=${{ matrix.fabric-api-version }}"
      - uses: actions/upload-artifact@v7
        with:
          name: XP-Orb-Trails-${{ matrix.minecraft-version }}
          path: build/libs/*.jar
